package main

import "time"

type AutoGenerated struct {
	Nhits      int `json:"nhits"`
	Parameters struct {
		Dataset  string `json:"dataset"`
		Timezone string `json:"timezone"`
		Rows     int    `json:"rows"`
		Format   string `json:"format"`
	} `json:"parameters"`
	Records []struct {
		Datasetid string `json:"datasetid"`
		Recordid  string `json:"recordid"`
		Fields    struct {
			GeoShape struct {
				Type        string    `json:"type"`
				Coordinates []float64 `json:"coordinates"`
			} `json:"geo_shape"`
			TactilePaving string    `json:"tactile_paving"`
			ID            string    `json:"_id"`
			GeoPoint2D    []float64 `json:"geo_point_2d"`
		} `json:"fields,omitempty"`
		Geometry struct {
			Type        string    `json:"type"`
			Coordinates []float64 `json:"coordinates"`
		} `json:"geometry"`
		RecordTimestamp time.Time `json:"record_timestamp"`
	} `json:"records"`
}
